### PR TITLE
Added the ability to use a proxy object to store properties to a file

### PR DESCRIPTION
**Pull request by trenta3**
We talked about this in [a ZeroTalk thread](http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1535667676_14mSHL2TBcqcLNcfpmg5jyGVS9RZia3FiX)

A simple usage example:
```javascript
 (async () => {
     var zeroframe = new ZeroFrame()
     var zeropage = new ZeroPage(zeroframe)
     var zerofs = new ZeroFS(zeropage)
     var storage = FileBackedStorage(zerofs, "data/users/" + zeroframe.site_info.auth_address + "/data.json")
     if (await storage.$exists)
         await storage.$load
     storage["a"] = 3
     await storage.$save$sign$publish
     storage["a"] = 5
     await storage.$load
     // Now storage["a"] == 3.
})()
```

### CODE REVIEW

**Comment by purplesyringa** [comment]
This looks nice, but I'd use (or at least support) this:

```javascript
if(await storage.$exists()) {
    await storage.$load();
}
await storage.$save().$sing().$publish();
```

**Comment by trenta3** [comment]
I'll change it soon to have function calls instead of simple attribute access.

I'm against the chain
```javascript
await storage.$save().$sing().$publish()
```
since each function returns a promise.

One would have to write
```javascript
await storage.$save()
await storage.$sign()
await storage.$publish()
```
or the already existing
```javascript
await storage.$save$sign$publish()
```
which was made for brevity since these actions are normally chained.

I'd like to add that every combination thereof can be already written, so it is legal to do:
```javascript
await storage.$save$sign()
// Custom code
await storage.$publish()
```

**Comment by purplesyringa** [comment]
Thank you.

**Comment by danimesq** [comment]
@imachug
Could you add it to documentation?

**Comment by purplesyringa** [comment]
Okay, once I add the docs for other classes.

**Comment by trenta3** [comment]
@imachug Sorry for this, but I noticed only now that the `JSON.stringify(inner)` should be changed to `JSON.stringify(inner, null, 2)` to benefit from the diff updates of json files.

**Comment by purplesyringa** [comment]
@trenta3 Maybe `JSON.stringify(inner, null, 1)` -- this is what ZeroNet core uses when signing `content.json`.

**Pull request merged**
